### ISSUE TITLE
Recommended way to install gem?

### ISSUE THREAD

**Issue by remore** [kateinoigakukun/ruby-compute-runtime#13]
While I was attempting to add a new gem dependency, I noticed that `require` fails with "cannot load such file -- xxx(gem name)" error message, despite that `$LOADPATH` is properly set. Here is the detail;

I was trying to add rack and diffy as an example. I added both dependencies by `$bundle install` command. With this set up, if I build and run by `$bundle exec ruby-compute-runtime` command, terminal shows the following;
```
INFO: Packaging gem: compute_runtime-0.1.0
INFO: Packaging gem: diffy-3.4.2
INFO: Packaging gem: rack-3.0.8
```

So yes, it is trying to package it. In fact, $LOADPATH looks properly set - if I dump it by `puts $LOADPATH` it shows below.
> ["/bundle/gems/rack-3.0.8/lib", "/bundle/gems/diffy-3.4.2/lib", "/bundle/gems/compute_runtime-0.1.0/lib", ...

Looking a bit further, I noticed that actually lib files are not added to the package. Specifically by [this commit](https://github.com/ruby/ruby.wasm/commit/f98b50c38e3d27329928e149f9f6c87cfe847f3f), currently only files declared in gemspec are added to the package. If I dump spec.files and spec.full_gem_path in `lib/ruby_wasm/packager/file_system.rb` inside [this block](https://github.com/ruby/ruby.wasm/blob/main/lib/ruby_wasm/packager/file_system.rb#L115-L131), it gives me below;

spec.files=[]
spec.full_gem_path=/root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/diffy-3.4.2

spec.files=["CHANGELOG.md", "CONTRIBUTING.md", "README.md"]
spec.full_gem_path=/root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.0.8

Fwiw, below is spec files saved in my local system for both gem (both are saved in `/root/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/specifications/`);
- [rack-3.0.8.gemspec](https://github.com/kateinoigakukun/ruby-compute-runtime/files/13885375/rack-3.0.8.gemspec.txt)
- [diffy-3.4.2.gemspec](https://github.com/kateinoigakukun/ruby-compute-runtime/files/13885377/diffy-3.4.2.gemspec.txt)

I might be adding gems in a wrong way in the first place though - is there a good way to add dependency at the moment? (if there is no good way I might need to end up with forcibly including gems by customizing some of these scripts)

**Comment by kateinoigakukun** [comment]
@remore Could you try https://github.com/ruby/ruby.wasm/pull/366 branch?

**Comment by remore** [comment]
Thanks for taking a look this quick! If I change [line 123](https://github.com/ruby/ruby.wasm/pull/366/files#diff-476cac7062dab7be2c5f507bf4c92c0440926c35356ff90a0c832c16b52756f5R123) to something like below, it worked! (just needed to make it recursive)
> relative_paths = Dir.glob('**/*', base: spec.full_gem_path)

**Comment by kateinoigakukun** [comment]
@remore You understand ruby.wasm much more than me 😂

**Comment by remore** [comment]
Haha no way but I'm getting a bit familiar thanks to your big help 🙏 Thanks a lot for that!

**Comment by remore** [comment]
I confirmed the merged https://github.com/ruby/ruby.wasm/pull/366 works for me. I'm not sure why I had to do `Dir.glob('**/*')` back then, probably just my mistake upon checking the behavior. Sorry for the false-positive, big thank you for the quick fix!
