### ISSUE TITLE
Some weird behavior observed when including stdlib

### ISSUE THREAD

**Issue by remore** [kateinoigakukun/ruby-compute-runtime#6]
If I enable stdlib by `--stdlib` param with a command like `$ ./exe/ruby-compute-runtime ./examples/demo.rb -o tmp/sample.wasm`, examples/demo.rb throws the following error;

```
2024-01-06T18:34:29.115391Z  INFO Listening on http://127.0.0.1:7676
2024-01-06T18:34:31.318312Z  INFO request{id=0}: handling request GET http://localhost:7676/hello?flip=left
/exe/demo.rb:7:in `<main>': uninitialized constant ComputeRuntime::Body (NameError)
2024-01-06T18:34:31.367534Z ERROR request{id=0}: WebAssembly exited with error: error while executing at wasm backtrace:
    0: 0x6fccae - <unknown>!__wasi_proc_exit
    1: 0x69e47c - <unknown>!_start

Caused by:
    Exited with i32 exit status 1
2024-01-06T18:34:31.367588Z  INFO request{id=0}: request completed using 120.7 MB of WebAssembly heap
2024-01-06T18:34:31.367619Z  INFO request{id=0}: request completed in 49ms
2024-01-06T18:34:31.368574Z ERROR There was an error handling the request error while executing at wasm backtrace:
    0: 0x6fccae - <unknown>!__wasi_proc_exit
    1: 0x69e47c - <unknown>!_start
```

If I remove `--stdlib` param, it works properly. I have not yet found the cause of this though, I noticed that this error is disappeared if I change the order of parameters to be passed to wasi-preset-args. Specifically, if I change the current call

https://github.com/kateinoigakukun/ruby-compute-runtime/blob/d8dafb4c7e2953bf463d9b45df7ace8c3b562be6/lib/compute_runtime/cli.rb#L33

to below (exchange `-I/lib` and `--disable=gems`)
> preset_args(output_file, output_file, "-I/lib", "--disable=gems", "/exe/#{File.basename(input_file)}")

then the right http response is returned to the browser, with the following warning is shown in the error log;

```
2024-01-06T18:24:19.153182Z  INFO Listening on http://127.0.0.1:7676/
2024-01-06T18:24:19.736477Z  INFO request{id=0}: handling request GET http://localhost:7676/hello?flip=left
sample-1704565448.wasm: warning: unknown argument for --disable: `/exe/demo.rb'
sample-1704565448.wasm: warning: features are [gems, error_highlight, did_you_mean, syntax_suggest, rubyopt, frozen_string_literal, rjit, yjit].
```

My best guess is the original error is gone because "-I/lib" takes effect in exchange for some new error in interpreting "--disable=gems". This theory adds up to me, since the original error (`uninitialized constant ComputeRuntime::Body`) is likely to occur when the program fails to load lib/compute_runtime.rb. Any thoughts or comments would be appreciated.

**Comment by kateinoigakukun** [comment]
Hmm, I couldn't reproduce the issue on my end. Which wasi-vfs version are you using? Would you mind trying it again with `cargo install --git https://github.com/kateinoigakukun/wasi-vfs wasi-vfs-cli --tag 0.5.1`?

**Comment by kateinoigakukun** [comment]
BTW I integrated wasi-vfs dependency into `ruby_wasm` gem and this project uses it https://github.com/kateinoigakukun/ruby-compute-runtime/pull/7, so we no longer need to install wasi-vfs CLI tool separately.

**Comment by remore** [comment]
With the latest env setup, it appears to be whether or not `--stdlib` is used is irrelevant. Rather, this issue is observed only on a guest OS running on Hyper-V. Please see #11 for more detail.
